server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: http://192.168.137.131:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: service-hosp # 路由id，自定义，只要唯一即可
          uri: lb://service-hosp # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates:
            - Path=/*/hosp/**
        - id: service-cmn
          uri: lb://service-cmn
          predicates:
            - Path=/*/cmn/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**
        - id: service-msm
          uri: lb://service-msm
          predicates:
            - Path=/*/msm/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/*/oss/**
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/*/order/**
        - id: service-statistics
          uri: lb://service-statistics
          predicates:
            - Path=/*/statistics/**
